name: first_project
description: "A new Flutter project."

publish_to: 'none' # Menandakan bahwa project ini tidak akan dipublikasikan ke pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  introduction_screen: ^3.1.0
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Baloo2
      fonts:
        - asset: assets/fonts/Baloo2-Bold.ttf
        - asset: assets/fonts/Baloo2-ExtraBold.ttf
        - asset: assets/fonts/Baloo2-Medium.ttf
        - asset: assets/fonts/Baloo2-Regular.ttf
        - asset: assets/fonts/Baloo2-SemiBold.ttf
