name: first_project
description: "A new Flutter project."

publish_to: 'none' # Menandakan bahwa project ini tidak akan dipublikasikan ke pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  http: ^1.3.0
  introduction_screen: ^3.1.0
  path_provider: ^2.1.5
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  sqflite: ^2.4.2

dev_dependencies:

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Baloo2
      fonts:
        - asset: assets/fonts/Baloo2-Bold.ttf
        - asset: assets/fonts/Baloo2-ExtraBold.ttf
        - asset: assets/fonts/Baloo2-Medium.ttf
        - asset: assets/fonts/Baloo2-Regular.ttf
        - asset: assets/fonts/Baloo2-SemiBold.ttf
